apiVersion: v1
kind: Service
metadata:
  name: house-price-service
spec:
  type: NodePort
  selector:
    app: house-price-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
